import {MigrationInterface, QueryRunner} from "typeorm";

export class FakePosts1623875431090 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
        insert into post (title, text, "creatorId", "createdAt") values ('Suture', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, '2021-02-09T05:55:12Z');
        insert into post (title, text, "creatorId", "createdAt") values ('White Mischief', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2021-03-31T08:39:43Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Model Couple, The (Le couple témoin)', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2020-10-13T03:41:27Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Story of Louis Pasteur, The', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2020-09-13T08:53:51Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Finding Forrester', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2020-11-09T14:17:06Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Ricky Gervais Live 3: Fame', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2020-07-08T07:18:25Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Battle of Los Angeles', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2020-09-11T17:05:27Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Waiting for Superman', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2020-11-25T01:37:18Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Bohème, La', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2021-03-14T20:28:49Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Kauwboy', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, '2021-01-15T09:41:54Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Blood, Sweat + Vinyl: DIY in the 21st Century', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1, '2020-10-14T21:41:46Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Friend Zone (Pagafantas)', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, '2021-05-21T14:18:39Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Black Peter (Cerný Petr)', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, '2020-11-26T21:15:01Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Incredible Shrinking Man, The', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2021-01-12T20:13:34Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Great Buck Howard, The', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, '2020-09-22T05:50:02Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Possession of David O''Reilly, The ', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, '2020-12-27T14:44:32Z');
        insert into post (title, text, "creatorId", "createdAt") values ('40 Guns to Apache Pass', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, '2020-11-14T23:54:25Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Harold & Kumar Escape from Guantanamo Bay', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, '2020-07-31T00:12:50Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Painted Lady', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2020-10-23T22:07:41Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Intern, The', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2020-12-10T15:22:59Z');
        insert into post (title, text, "creatorId", "createdAt") values ('8:28 am (8 Uhr 28)', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2020-08-10T00:21:03Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Stunt Rock', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, '2021-03-15T11:03:04Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Other Woman, The', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2021-04-08T18:48:28Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Beach Girls and the Monster, The', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2021-02-27T23:20:23Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Two Weeks in September', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2020-08-19T02:14:42Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Fate (Yazgi)', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-05-08T22:38:28Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Hijacking, A (Kapringen)', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, '2020-10-26T21:17:12Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Filthy Gorgeous: The Bob Guccione Story', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, '2020-07-06T11:33:00Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Warrior', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2020-09-06T20:24:11Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Boy Interrupted', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, '2021-06-07T11:02:58Z');
        insert into post (title, text, "creatorId", "createdAt") values ('And Now My Love (Toute une vie)', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2021-03-08T00:12:53Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Four Shades of Brown (Fyra nyanser av brunt)', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2020-08-04T00:35:05Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Attila (Attila the Hun)', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, '2020-09-29T02:51:56Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Craig''s Wife', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, '2020-12-24T02:38:03Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Man with the Golden Arm, The', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2021-05-24T19:20:43Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Carrington', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2020-09-01T09:25:46Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Dead Awake', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2021-02-24T22:39:49Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Calvary', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2020-10-27T10:15:33Z');
        insert into post (title, text, "creatorId", "createdAt") values ('That Darn Cat!', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2020-12-16T12:37:20Z');
        insert into post (title, text, "creatorId", "createdAt") values ('It''s My Mother''s Birthday Today', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, '2020-10-29T14:08:20Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Cube', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, '2021-01-05T18:26:28Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Blood Relatives (Liens de sang, Les)', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, '2020-08-19T08:08:28Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Pontiac Moon', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1, '2020-10-12T17:20:30Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Execution of P, The (Kinatay)', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2021-01-08T02:49:35Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Hide and Seek', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2020-11-10T06:04:41Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Boogie Nights', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2021-04-22T06:14:34Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Invitation to the Dance', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2021-01-31T22:58:11Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Hero (Ying xiong)', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2020-10-13T09:53:35Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Leviathan', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2021-04-03T20:53:42Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Coming Out', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, '2020-12-04T23:14:34Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Papa''s Delicate Condition', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2021-01-20T04:22:12Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Funky Forest: The First Contact', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2020-10-03T12:25:44Z');
        insert into post (title, text, "creatorId", "createdAt") values ('From the Sky Down', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2020-10-23T14:13:15Z');
        insert into post (title, text, "creatorId", "createdAt") values ('The Infinite Man', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, '2020-08-26T17:10:12Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Texas Rangers', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 1, '2021-01-30T08:26:15Z');
        insert into post (title, text, "creatorId", "createdAt") values ('When a Stranger Calls', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2021-04-05T14:05:53Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Passenger 57', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, '2021-04-13T15:48:14Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Happiest Girl in the World, The (Cea mai fericita fata din lume)', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2021-02-12T04:45:13Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Philomena', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2020-09-25T17:36:51Z');
        insert into post (title, text, "creatorId", "createdAt") values ('File on Thelma Jordan, The', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2021-05-31T18:48:22Z');
        insert into post (title, text, "creatorId", "createdAt") values ('American Carol, An', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2020-06-22T21:43:30Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Physical Evidence', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2020-07-21T00:30:10Z');
        insert into post (title, text, "creatorId", "createdAt") values ('South of the Border', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-05-14T20:03:51Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Blindness', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, '2020-12-14T23:50:02Z');
        insert into post (title, text, "creatorId", "createdAt") values ('My Name Is Joe', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2021-03-21T15:24:36Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Lucky Numbers', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2020-10-06T22:37:22Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Kiss Kiss Bang Bang', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-01-08T20:59:29Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Big Bad Love', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2020-09-22T01:53:44Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Closed Circuit', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2021-03-04T09:59:36Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Daltry Calhoun', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2020-08-18T03:25:36Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Charlie Chan at Treasure Island', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, '2021-05-23T05:01:51Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Vacancy', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-01-02T01:16:17Z');
        insert into post (title, text, "creatorId", "createdAt") values ('JFK: The Smoking Gun', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, '2020-11-27T19:12:18Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Involuntary (De ofrivilliga)', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, '2020-09-20T10:13:25Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Scapegoat, The', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, '2021-03-28T10:10:05Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Blue Streak', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2020-11-22T11:04:09Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Human Race, The', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2020-12-29T03:15:52Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Professionals, The', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2021-03-22T05:38:11Z');
        insert into post (title, text, "creatorId", "createdAt") values ('When in Rome', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2020-09-20T12:44:50Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Mean Machine', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2020-11-21T02:26:16Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Purge, The', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, '2021-04-09T10:39:22Z');
        insert into post (title, text, "creatorId", "createdAt") values ('The Stranger''s Return', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2021-02-06T08:36:51Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Marine, The', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-02-03T03:56:57Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Roadie', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2020-10-15T00:38:41Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Places in the Heart', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, '2021-04-22T05:22:08Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Ghost, The', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2021-02-12T22:32:22Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Poetry (Shi)', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2021-02-07T03:31:24Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Caught Up', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2020-11-27T12:49:46Z');
        insert into post (title, text, "creatorId", "createdAt") values ('What''s New, Pussycat', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, '2021-05-12T21:49:34Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Sidekicks', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2021-02-25T07:18:18Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Run If You Can', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, '2021-03-04T10:15:42Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Eddie Murphy Delirious', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2020-11-30T20:52:29Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Abduction', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2020-09-03T08:10:40Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Night of the Zombies (a.k.a. Batallion of the Living Dead)', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, '2021-03-11T08:39:07Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Gypsy', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2020-12-23T04:24:57Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Living with Wolves', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2020-12-01T06:50:00Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Bigger Than Life', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-04-02T18:03:54Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Surviving Picasso', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2021-05-21T08:17:33Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Elephant Boy', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2020-10-31T00:07:19Z');
        insert into post (title, text, "creatorId", "createdAt") values ('Millionaire for Christy, A (Golden Goose) (No Room for the Groom)', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2020-09-19T08:15:28Z');
                
        `);
    }

    public async down(_: QueryRunner): Promise<void> {
    }

}
